// Code generated by MockGen. DO NOT EDIT.
// Source: vfs.go

// Package vfs is a generated GoMock package.
package vfs

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVirtualFileSystem is a mock of VirtualFileSystem interface.
type MockVirtualFileSystem struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualFileSystemMockRecorder
}

// MockVirtualFileSystemMockRecorder is the mock recorder for MockVirtualFileSystem.
type MockVirtualFileSystemMockRecorder struct {
	mock *MockVirtualFileSystem
}

// NewMockVirtualFileSystem creates a new mock instance.
func NewMockVirtualFileSystem(ctrl *gomock.Controller) *MockVirtualFileSystem {
	mock := &MockVirtualFileSystem{ctrl: ctrl}
	mock.recorder = &MockVirtualFileSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualFileSystem) EXPECT() *MockVirtualFileSystemMockRecorder {
	return m.recorder
}

// CreateFile mocks base method.
func (m *MockVirtualFileSystem) CreateFile(username, foldername, filename, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFile", username, foldername, filename, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFile indicates an expected call of CreateFile.
func (mr *MockVirtualFileSystemMockRecorder) CreateFile(username, foldername, filename, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFile", reflect.TypeOf((*MockVirtualFileSystem)(nil).CreateFile), username, foldername, filename, description)
}

// CreateFolder mocks base method.
func (m *MockVirtualFileSystem) CreateFolder(username, foldername, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFolder", username, foldername, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFolder indicates an expected call of CreateFolder.
func (mr *MockVirtualFileSystemMockRecorder) CreateFolder(username, foldername, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFolder", reflect.TypeOf((*MockVirtualFileSystem)(nil).CreateFolder), username, foldername, description)
}

// DeleteFile mocks base method.
func (m *MockVirtualFileSystem) DeleteFile(username, foldername, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", username, foldername, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockVirtualFileSystemMockRecorder) DeleteFile(username, foldername, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockVirtualFileSystem)(nil).DeleteFile), username, foldername, filename)
}

// DeleteFolder mocks base method.
func (m *MockVirtualFileSystem) DeleteFolder(username, foldername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFolder", username, foldername)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFolder indicates an expected call of DeleteFolder.
func (mr *MockVirtualFileSystemMockRecorder) DeleteFolder(username, foldername interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFolder", reflect.TypeOf((*MockVirtualFileSystem)(nil).DeleteFolder), username, foldername)
}

// DeleteUser mocks base method.
func (m *MockVirtualFileSystem) DeleteUser(username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockVirtualFileSystemMockRecorder) DeleteUser(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockVirtualFileSystem)(nil).DeleteUser), username)
}

// GetByUsername mocks base method.
func (m *MockVirtualFileSystem) GetByUsername(username string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", username)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockVirtualFileSystemMockRecorder) GetByUsername(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockVirtualFileSystem)(nil).GetByUsername), username)
}

// ListFiles mocks base method.
func (m *MockVirtualFileSystem) ListFiles(username, foldername, sortBy, order string) ([]*File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", username, foldername, sortBy, order)
	ret0, _ := ret[0].([]*File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockVirtualFileSystemMockRecorder) ListFiles(username, foldername, sortBy, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockVirtualFileSystem)(nil).ListFiles), username, foldername, sortBy, order)
}

// ListFolders mocks base method.
func (m *MockVirtualFileSystem) ListFolders(username, sortBy, order string) ([]*Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFolders", username, sortBy, order)
	ret0, _ := ret[0].([]*Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFolders indicates an expected call of ListFolders.
func (mr *MockVirtualFileSystemMockRecorder) ListFolders(username, sortBy, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFolders", reflect.TypeOf((*MockVirtualFileSystem)(nil).ListFolders), username, sortBy, order)
}

// ListUsers mocks base method.
func (m *MockVirtualFileSystem) ListUsers() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockVirtualFileSystemMockRecorder) ListUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockVirtualFileSystem)(nil).ListUsers))
}

// Load mocks base method.
func (m *MockVirtualFileSystem) Load() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockVirtualFileSystemMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockVirtualFileSystem)(nil).Load))
}

// RegisterUser mocks base method.
func (m *MockVirtualFileSystem) RegisterUser(username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", username)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockVirtualFileSystemMockRecorder) RegisterUser(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockVirtualFileSystem)(nil).RegisterUser), username)
}

// RenameFolder mocks base method.
func (m *MockVirtualFileSystem) RenameFolder(username, foldername, newFoldername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameFolder", username, foldername, newFoldername)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameFolder indicates an expected call of RenameFolder.
func (mr *MockVirtualFileSystemMockRecorder) RenameFolder(username, foldername, newFoldername interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameFolder", reflect.TypeOf((*MockVirtualFileSystem)(nil).RenameFolder), username, foldername, newFoldername)
}

// Save mocks base method.
func (m *MockVirtualFileSystem) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockVirtualFileSystemMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockVirtualFileSystem)(nil).Save))
}
