// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/blackhorseya/iscool-assessment/internal/repo/folder"
	"github.com/blackhorseya/iscool-assessment/internal/repo/user"
	vfs3 "github.com/blackhorseya/iscool-assessment/internal/vfs"
	vfs2 "github.com/blackhorseya/iscool-assessment/pkg/vfs"
)

// Injectors from wire.go:

func NewVFSWithJSON(path string) (vfs2.VirtualFileSystem, error) {
	userManager, err := user.NewJSONFile(path)
	if err != nil {
		return nil, err
	}
	folderManager, err := folder.NewJSONFile(path)
	if err != nil {
		return nil, err
	}
	virtualFileSystem := vfs3.New(userManager, folderManager)
	return virtualFileSystem, nil
}

func NewVFSWithSystem(path string) (vfs2.VirtualFileSystem, error) {
	userManager, err := user.NewSystem(path)
	if err != nil {
		return nil, err
	}
	folderManager, err := folder.NewSystem(path)
	if err != nil {
		return nil, err
	}
	virtualFileSystem := vfs3.New(userManager, folderManager)
	return virtualFileSystem, nil
}
